name: Python CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.7

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run pytest
      run: pytest test/

    - name: Run mypy
      run: mypy src/

    - name: Run black
      run: black --check --diff src/

    - name: Run isort
      run: isort --check-only --diff src/

    - name: Run flake8
      run: flake8 src/
